spring:
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: true
    jackson:
        serialization:
            INDENT_OUTPUT: false
    liquibase:
        contexts: prod
        drop-first: true