spring:
    jpa:
        hibernate:
          ddl-auto: validate
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
          hibernate:
            temp:
              use_jdbc_metadata_defaults: false
        open-in-view: false
    datasource:
        url: jdbc:postgresql://localhost:5432/simpleapi_app_db
        username: simpleapi_app
        data-password: q1w2e3
        driver-class-name: org.postgresql.Driver
    jackson:
        serialization:
            INDENT_OUTPUT: true
    liquibase:
        change-log: classpath:/liquibase/master.yml
server:
    port: 8080